spring:
  config:
    import: "optional:configserver:http://configserver-service:80/"

eureka:
  client:
    serviceUrl:
      defaultZone: http://team6-eureka-server:8761/eureka
      # defaultZone: http://eurekaserver-service:80/eureka/