apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper
  namespace: group1-team6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-zookeeper
  template:
    metadata:
      labels:
        app: kafka-zookeeper
    spec:
      containers:
        - name: zookeeper
          image: k8s-vga-worker1:5000/group1-team6-cha-zoo:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_LISTENER_PORT
              value: "2181"
        - name: kafka
          image: k8s-vga-worker1:5000/group1-team6-cha-kafka:latest
          ports:
            - containerPort: 9093
          env:
            - name: KAFKA_ADVERTISED_LISTENER
              value: INSIDE_KAFKA:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_LISTENER_NAMES
              value: INSIDE_KAFKA
            - name: KAFKA_LISTENER_PORT
              value: "9093"
            - name: KAFKA_LISTENER_INTERNAL_PORT
              value: "9095"
            - name: KAFKA_LISTENER_HTTP_PORT
              value: "9094"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper-sv
  namespace: group1-team6
spec:
  ports:
    - port: 9093
      targetPort: 9093  # 포트 정의를 targetPort로 설정
    - port: 2181
      targetPort: 2181  # 포트 정의를 targetPort로 설정
  selector:
    app: kafka-zookeeper  # Deployment의 selector와 일치해야 함