server:
  port: 8099


spring:
  application:
    name: stream
  cloud:
    stream:
      bindings:
        output:
          destination: cha-topic  # 메시지를 보낼 Kafka 토픽 이름
          content-type: application/json
        input:
          destination: cha-topic  # 메시지를 받을 Kafka 토픽 이름
          content-type: application/json
      kafka:
        binder:
          brokers: kafka.group1-team3:9092  # Kafka 브로커 주소
eureka:
  instance:
    preferIpAddress: true
    lease:
      renewal:
        interval:
          in:
            seconds: 10
      expiration:
        duration:
          in:
            seconds: 30
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://team6-eureka-server:8761/eureka
