server:
  port: 8099


  
  # cloud:
  #   stream:
  #     bindings:
  #       output:
  #         destination: rabbit-exchange  # RabbitMQ 교환기
  #         binder: rabbit-binder         # RabbitMQ 바인더를 'rabbit-binder'로 지정
  #       input:
  #         destination: cha-topic  # 메시지를 받을 Kafka 토픽 이름
  #         group: cha-group
  #         binder: kafka-binder # RabbitMQ 바인더를 'rabbit-binder'로 지정

spring:
  application:
    name: stream
  cloud:
    stream:
      bindings:
        kafka-output:
          destination: cha-topic  # Kafka로 메시지 전송
        kafka-input:
          destination: cha-topic   # Kafka에서 메시지 수신
        rabbit-output:
          destination: rabbit-output-queue  # RabbitMQ로 메시지 전송
        rabbit-input:
          destination: rabbit-input-queue   # RabbitMQ에서 메시지 수신
      binders:
        kafka-binder:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: 192.168.100.221:30641 # Kafka 브로커의 주소 설정
        rabbit-binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.100.221  # RabbitMQ 호스트 주소
                port: 306638
                username: guest
                password: guest
                virtual-host: /



# eureka:
#   instance:
#     preferIpAddress: true
#     lease:
#       renewal:
#         interval:
#           in:
#             seconds: 10
#       expiration:
#         duration:
#           in:
#             seconds: 30
#   client:
#     fetchRegistry: true
#     registerWithEureka: true
#     serviceUrl:
#       defaultZone: http://team6-eureka-server:8761/eureka
